trigger:
  branches:
    include:
      - master  # o la rama que uses para tus despliegues

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'backendSistemaInventario'  # O tu registro en Render, si usas Docker Hub

jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy Docker container to Render'
    steps:

      - task: Checkout@2
        displayName: 'Checkout source code'

      # Construir la imagen Docker
      - task: Docker@2
        displayName: 'Build Docker image'
        inputs:
          containerRegistry: $(dockerRegistryServiceConnection) # Usa tu servicio de contenedor (Docker Hub o Render)
          dockerfile: 'backendSistemaInventario/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest

      # Desplegar la imagen a Render (puedes usar Docker Push o Render API)
      - task: AzureCLI@2
        displayName: 'Deploy to Render'
        inputs:
          azureSubscription: 'Azure for Students'  # Si es necesario, configúralo en la configuración de Azure DevOps
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Aquí podrías usar Render CLI o la API de Render para hacer el despliegue
            # Render CLI necesita estar instalado en el agente. Si prefieres usar Docker Hub:
            # docker push <docker-repository>:$(Build.BuildId)
            curl -X POST https://api.render.com/deployments \
                 -H "Authorization: Bearer rnd_zTf4ojtecctqBDNOkwRAyr7nTkeC" \
                 -H "Content-Type: application/json" \
                 -d '{"branch": "master", "serviceId": "srv-cvh2bjlrie7s73ejbm8g"}'
